name: process_visor
description: Manages (start, stop, restart) an OS process.
version: 0.2.1
homepage: https://github.com/agilord/process_visor
topics:
  - cli
  - process
  - supervisor

environment:
  sdk: '^3.8.0'

# dependencies:

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
