name: process_visor
description: Manages (start, stop, restart) an OS process, switches it dynamic context and call priorities.
version: 0.3.0
homepage: https://github.com/agilord/process_visor
topics:
  - cli
  - process
  - supervisor

environment:
  sdk: '^3.9.0'

# dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.14
